### ISSUE TITLE
Hyperledger FireFly Graduation

### ISSUE THREAD

**Issue by nguyer** [hyperledger/tsc#165]
The FireFly Community would like to propose moving from Incubating Project status to Graduated Project status. I will open a PR against https://github.com/hyperledger/hyperledger-hip with the details of our proposal, and I will link it back to this issue. I am happy to discuss any questions or feedback that the TOC has on that PR, or to chat about it on a call if desired.

If possible, we would love to discuss this topic and hold a vote at the next TOC meeting on 2023-09-21. We are working toward having maintainers from each of the different companies represented in the project present for discussion that day.

Thanks!

Nicko

**Comment by nguyer** [comment]
Proposal has been submitted in https://github.com/hyperledger/hyperledger-hip/pull/11

**Comment by tkuhrt** [comment]
**Approved at September 21, 2023 TOC meeting**
