### ISSUE TITLE
Whitepaper Taskforce: Role of Blockchain in the Elections process

### ISSUE THREAD

**Issue by sharmawiki** [hyperledger/tsc#18]
**Introduction/background material:**
Various government and public agencies have experimented with using Blockchain as part of their technology stack while conducting elections from a fair and transparent perspective. The idea behind this task force would be
- to collect the information already available in the public domain,
- reach out to various entities who have developed solutions or experimented with blockchain in this domain,
- share lessons learnt, benefits, issues, concerns and disadvantages,
- understand from others viewpoints (optionally mention them), share our point of view highlighting which parts of the process are Blockchain more suitable to;
- share which technologies can work together to help enhance the transparency and trust in the system. 
- conclude.
- Optionally, as part of this we will also target to come up with a reference architecture for the same.

**Task to be completed:**
- [ ] Create a Whitepaper that highlights the current landscape of Blockchain in Elections and also discuss what the future holds for the technology in this domain.

**List of deliverables or work products:**
Whitepaper

**Time to complete (no more than 6 months):** 6 Months

**Leader:** Vikram Sharma

**Initial participant list**
Amol Kulkarni
Kamlesh Nagware
Aruna S M
Madhu Bhatia, 
Rajesh Krishnan, Sr Architect, Dell
Sunil Kapadia
Samrat Kishor
Anant Avinashi
Ishan Roy, Head Tamil Nadu eGovernance
Sowjanya Segu, 
Anil Dongre, Sr Architect, Persistent
Aniket Dhar, 
Dhyan Appachu Bollachettira, Founder, Shambala
Pritam Singh
Ranjeet Singh
Shivendra Yadav
Ravi Shankar Gupta
Sandeep Srivastava

**Comment by tkuhrt** [comment]
The TSC [reviewed this proposal on November 4](https://wiki.hyperledger.org/download/attachments/58860791/TSC%202021%20NOV%2004.mp4?api=v2). While the TSC does not want to discourage the interested parties from working on a paper, there was a concern with this being an officially recognized whitepaper from the Hyperledger Foundation. Whitepapers are reports or guides that inform readers concisely about a complex issue and present the issuing body's philosophy on the matter.

**Comment by tkuhrt** [comment]
The TSC [discussed this proposal further on November 11](https://wiki.hyperledger.org/display/TSC/2021+11+11+TSC+Meeting+Record). @arsulegai has connected with the Public Sector SIG, and they will be taking the work on within the confines of the SIG.
