### ISSUE TITLE
DCI Working Group: Inclusive Naming Proposal

### ISSUE THREAD

**Issue by arsulegai** [hyperledger/tsc#19]
Detailed proposal can be found here https://wiki.hyperledger.org/display/TSC/DCI+Working+Group%3A+Inclusive+Naming+Proposal

**Comment by petermetz** [comment]
Update: I've added the fresh links to the proposal for DCI Lint which now show the screencast tutorial on how to introduce automatic pull request DCI linting for any HL or HL Labs project.

**Comment by ryjones** [comment]
Approved by voice vote on [17 FEB 2022](https://wiki.hyperledger.org/display/TSC/2022+02+17+TSC+Meeting+Record)
