### ISSUE TITLE
Proposal for TSC Members to Attend (Pseudo)random Meetings

### ISSUE THREAD

**Issue by hartm** [hyperledger/tsc#21]
**Background:**
One thing that could possibly benefit the TSC (and Hyperledger as a whole) is more awareness of and interaction with different projects.  This could spur more cross-project collaboration, less fragmentation between projects, and, in general, more project happiness with the TSC.

**Proposal:**
The TSC collectively requests that each TSC member attend one project meeting a month for a project with which they are unaffiliated and have not been a contributor (and, ideally, one that they have not attended before).  Whether people want to introduce themselves and participate or just listen wouldn't matter too much: just attendance would be great.  

On the TSC wiki, a page will be created to keep track of meeting attendance in some kind of spreadsheet (either public, if people are OK with it, or private to the TSC) with the main purpose being that TSC members know which meetings other members have attended so that TSC members can stagger their attendance across many project meetings.  This is because this initiative will be much more effective if TSC members attend many different meetings rather than all attending, say, a meeting of what is perceived to be a currently popular project.

We also propose to include SIGs and working groups as possible options for TSC members to attend.  Finally, if non-TSC maintainers wish to be included, we propose to include them as well.

The time commitment--one meeting a month--should be pretty small, and the hope is that going to these meetings would be very informative for TSC members, and an opportunity for projects who aren't strongly connected to the TSC to ask questions about HL as a whole if they want.

We also propose that TSC members be invited (but not required) to report back during TSC meetings about anything they found interesting, noteworthy, or that needs addressing in some sort of brief discussion.  We also suggest that TSC members that adhere to this schedule be rewarded with food and/or drink by the HL staff at the next in-person event.

**Comment by hartm** [comment]
Note:  Add in suggestion that TSC members should rotate through different groups' meetings, not just attend one repeatedly.

**Comment by knagware9** [comment]
Its good initiative +1

**Comment by tkuhrt** [comment]
Approved during December 16, 2021 TSC meeting
Votes:
* 12 approved
* 1 abstained
* 2 absent
