### ISSUE TITLE
Projects who have not submitted their TSC Quarterly Project Update may be moved to Dormant state after a TSC discussion and possible vote

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/tsc#22]
TSC Quarterly Project Updates are a way for the TSC to understand the state and community health of Hyperledger projects. The TSC Vice Chair reaches out to projects when they miss submitting their TSC Quarterly Project Update to remind the projects that they have a report due. The following are the reach out mechanisms that are used:
1. Directly reaching out to the last submitter of the project's quarterly update
2. Reaching out via the project's mailing list
3. Reaching out via the project's official chat channel

If the TSC Vice Chair is unable to reach someone in the project and an entire quarter has gone by since the report was due, then the TSC will discuss and determine if there should be a vote on moving that project to a Dormant state.

**Comment by tkuhrt** [comment]
@hyperledger/tsc : Is a entire quarter the right time frame or would a month be enough time?

**Comment by shemnon** [comment]
my thought is that if it's less than a quarter two full requests per channel need to be attempted.

Also, I can think of a number of reasons why a month without communications may occur, but not three months.  I'm weekly in favor of three months but if a consensus forms around a month I would support that.

**Comment by lehors** [comment]
I would agree with Danno and don't think there is any reason to rush either.

**Comment by ryjones** [comment]
@lehors I don't think there is a rush, but I would prefer it to be something less than a quarter (one report that is less than a quarter late)

**Comment by shemnon** [comment]
Cumulative of 13 weeks over the last 4 reports?  In the case discussed on the call it's been a habitual issue.

**Comment by shemnon** [comment]
And just because we can vote doesn't mean we have to vote (although we should examine the evidence)

**Comment by vaporos** [comment]
The bar for this should be very high, not low. Projects might have a hard time finding someone willing or interested in doing the busy work of writing a report which is viewed by very few people. Missing multiple updates in a row at minimum. We've been pretty consistent in submitting these for projects I'm involved in, but that is because we have individuals on the projects that are exceptionally organized to coordinate multiple developers to help write them up. Its easy to see how other teams could have less ideal dynamics.

Also, what's the motivation? Punishment for not submitting these reports, or actually culling projects? If punishment, then maybe another approach is called for. If culling, then it should be a discussion with the project maintainers (if available), not presented as a whimsical TSC vote.

**Comment by shemnon** [comment]
This is why I asked for the list of services that HL provides to projects.  Quarterly reports I view as a quid-pro-quo - you give us a quarterly update on how things are going and Hyperledger pays bills for the following services to help you build.

And it's more than missing a few reports.  One project of concern is totally incommunicado.  All pings have been ignored. That's why it's a vote for dormant status, not a mechanical requirement it goes to dormancy. Situations like you describe where it's truly an issue of not finding someone willing to spend 30 miuntes a quarter filling out a form I expect to get leniency.  But when a project goes dark (like Composer did) not signaling early enough what is going on leads to problems.

**Comment by lehors** [comment]
Not that it changes your point @shemnon but, for the record, Composer never went dark. The maintainers communicated all along their intent so, that's not the reference you want to use for this. Just saying. :-)

**Comment by knagware9** [comment]
I think 3 requests to submit the project report after the report deadline reach. If not submitted within a month after last request TSC vote can be done to decide project status.

**Comment by jimthematrix** [comment]
I agree that the bar to put a project to dormancy should be high, but the bar for a TSC pro-active review does not necessarily need to be high, in fact a low bar for TSC to review (and possibly vote) on a project's viability should be a good thing. It'll allow the TSC and the community as a whole to periodically evaluate the health of a project. More attention should be beneficial to the project.

So I would also lean toward a more aggressive schedule, like if a project is not able to provide a quarterly report 4 weeks in a row, and the committers will have been contacted multiple times, then its status should be brought up for discussion in the TSC.

The TSC of course should carefully review the data (git repo activities, chats, community calls, etc.) to make informed decisions. Preferably the project committers should be present on the call to defend the case but with the understanding that it may not be possible (and thus their presence not a requirement) given the incommunicado that will have led to the situation.

**Comment by arsulegai** [comment]
Here's my take on the issue:

**To Solve:** Encourage project teams to send in quarterly status on time.

**Proposal:** Introduce a new state within the project's lifecycle, let's call it `Not Active` for the sake of this proposal. A project enters this state if a communication to project team is not successful. Requesting quarterly report can be one of the many reasons why a project enters this state. Also, any community member may bring up their concern to the TSC in the act of reaching out to the project team. The TSC may refer to project activities through LF insights, GitHub etc even before reaching out to the project team. Optionally can seek a response from project team for the larger community raised concerns.

Let's define a number `n` (for example, 3), the number of times a project has been reported as `Not Active`. If a project exceed this number `n`, then the TSC gets to vote on moving the project to enter the Dormant state. Also, let's define the frequency of reporting a project as `Not Active` (for example, once in 2 weeks), the same project for any reason cannot be reported as `Not Active` within this time range.

The proposal may sound similar to what has been discussed already, but framing it this way would give the benefit of doubt to project teams. We shall encourage projects to nurture well, get through their difficult times and shine bright. Having a transition state in this case before forcing upon Dormant state will help in avoiding miscommunications. In addition it provides a pathway for the larger community driven feedback mechanism.

**Opens:**
1. What benefits at HF differentiates and motivates a project team to strive to graduate? (We had a brief discussion earlier, shall continue to invest in more time on refining it).
2. How do we reflect the current state of project in real-time to the consumers of project? (This could in a way directly impact the project. A consumer of a project wouldn't continue investing their time/resources on it, if the project team is not responsive/active anymore. This will force the project team to not miss out on HF guidelines).

**Comment by tkuhrt** [comment]
Based on a discussion in the TOC meeting of October 13th, we believe that there is no further action needed for this issue. The [project lifecycle](https://github.com/hyperledger/toc/blob/gh-pages/project-lifecycle.md) already allows for the TOC to move a project to dormant state upon request, which could be a request from TOC after not getting response to the request for project updates.

> Projects enter the *Dormant* state when the normal functions are suspended or slowed down for a period of time. The TOC decides to move a project to or from the *Dormant* state upon request.
