### ISSUE TITLE
Please deprecate the Avalon project

### ISSUE THREAD

**Issue by ryjones** [hyperledger/tsc#23]
[Eugene Yarmosh](https://github.com/EugeneYYY) has [requested the Avalon project be deprecated](https://github.com/hyperledger/avalon/blob/main/MAINTAINERS.md).

**Comment by arsulegai** [comment]
Sad and unfortunate to see Avalon's deprecation.

It would help if we can capture major reasons. These reasons will help in deciding the grounds for making decisions. Let's keep a door open for future possible resurrection.

**Comment by hartm** [comment]
I don't think that deprecation should always be seen as sad and unfortunate.  It's the natural project lifecycle!  Some things in the greenhouse aren't going to live forever.

I do agree with Arun that we should capture major reasons for deprecation.  It will always be the case that the contributors wanted to move on:  the question is why.

**Comment by ryjones** [comment]
Approved by voice vote 20 JAN 2022. https://wiki.hyperledger.org/display/TSC/2022+01+20+TSC+Meeting+Record
