### ISSUE TITLE
Move project reports to GitHub

### ISSUE THREAD

**Issue by ryjones** [hyperledger/tsc#43]
# Move project reports to GitHub

### Transparency

1. It is trivial for someone to mark a report as reviewed by a member of the TOC. Using GitHub, only someone that controls a specific account can vote as that account.
2. The history of a project can be reviewed using standard tools like `git-blame`

### Durability

1. If someone edits a report in the wiki after approval, it is difficult to notice.
2. Important artifacts for the history of Hyperledger have been lost, due to being kept in Google Docs or similar. [The original proposal documents for Hyperledger Sawtooth, for instance, are lost.](https://wiki.hyperledger.org/display/TSC/Proposals+through+2018)

### Process Proposed

1. A template will be created for filing a PR
2. Once a quarter, projects will use this template to file a PR
3. Once approved by TOC, PR will be merged
4. Once merged, website will be updated (much like [merging a PR](https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/225) in Labs updates the [Hyperledger Labs](https://labs.hyperledger.org/) website)

**Comment by tkuhrt** [comment]
@ryjones : Which repo would you suggest? This one? Or governance? Or some other?

**Comment by ryjones** [comment]
@tkuhrt I think this one, but I don't have strong feelings about it. I could be easily convinced governance is the right home.

**Comment by lehors** [comment]
Hi @ryjones Can you please explain what the advantages would be? Is it just to move away from the wiki?
I'm not against it but it seems to me that this implies a more complex process than what we have today with the wiki. Presumably, new reports would have to be submitted via PRs, right? Who would merge them? On what basis?
This seems to require some form of document flow/process we don't have (nor need) with the wiki.
But maybe you have some other model in mind?

**Comment by ryjones** [comment]
Hi @lehors . My thoughts are, a PR is submitted, commentary from TOC members and maintainers is captured as review comments. Once a TOC member is satisfied, they "approve" the PR. Once all TOC members approve, it's merged.

One of the big wins is TOC members can only vote for themselves. Right now, someone from the TOC could check off everyone's boxes and it would be annoying to prove or disprove that it happened. Another win is GitHub APIs could be easily called - right now, getting data from GitHub into reports is kind of a hack. I'm not super invested in this idea, but I would like to move stuff away from the Wiki to a more controlled place. It's easy for me to change "reviewers" by editing the TOC team; it's easy for me to create checklist items and the like; it's much easier to edit the templates, as well.

**Comment by arsulegai** [comment]
> @tkuhrt I think this one, but I don't have strong feelings about it. I could be easily convinced governance is the right home.

How about using the governance repository? The TOC repository has discussion and decision items from the TOC. The governance repository already seems to be capturing project charters. In addition, a link to [governance rendered site](https://hyperledger.github.io/governance/) from this repository would help.

**Comment by ryjones** [comment]
[Approved by voice vote 26 JAN 2023](https://wiki.hyperledger.org/display/TSC/2023+01+26+TOC+Meeting+Record)
