### ISSUE TITLE
Task Force Proposal: Project Best Practices

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/tsc#45]
# Introduction/background material
In the [first meeting of the 2023 TOC](https://wiki.hyperledger.org/display/TSC/2023+01+12+TOC+Meeting+Record), @denyeart suggested we look at creating best practices for projects
 
# Task to be completed
Document/Gather best practices for projects in a single location.

# List of deliverables or work products
- [ ] gather list of current best practices
- [ ] determine gaps for other best practices that should be documented

# Time to complete (no more than 6 months)
May 2023.

# Leader
Dave Enyeart

# Initial participant list
* Venkatraman Ramakrishna (Rama)
* Tracy Kuhrt
* Jim Zhang

[Wiki page](https://wiki.hyperledger.org/display/TF/Project+Best+Practices+task+force)

**Comment by MiirzaBaig** [comment]
How can i contribute here?

**Comment by tkuhrt** [comment]
Completed with #111 and #112
