### ISSUE TITLE
Task Force Proposal: Supported Project

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/tsc#51]
# Introduction/background material
With the most recent update to the [Hyperledger Charter](https://www.hyperledger.org/about/charter), "Supported Projects" were introduced.

> The scope of the Hyperledger Foundation includes supporting various open technical projects (including open source software, open standards / specifications, open data and other open projects, collectively, “Technical Projects”).Technical Projects can either be overseen by (i) the Technical Oversight Committee of the Hyperledger Foundation (such Technical Projects, “TOC Projects”), or (ii) separate technical oversight pursuant to a technical charter specific to such Technical Project (such Technical Projects, “Supported Projects”).

As such, the TOC needs to better understand the impact to the [TOC Governing Documents](https://toc.hyperledger.org/), specifically, the [project proposal process](https://hyperledger.github.io/hyperledger-hip/), [project lifecycle](https://toc.hyperledger.org/project-lifecycle.html), and any other places where "Supported Projects" might need to be reflected.

# Task to be completed
Update Hyperledger governing documents and other places that need to handle "Supported Projects".

# List of deliverables or work products
- [ ] Determine list of places that need to be updated to handle "Supported Projects"
- [ ] Update each place identified above

# Time to complete (no more than 6 months)
TBD

# Leader
TBD

# Initial participant list
* Tracy Kuhrt

**Comment by a-god-of-death** [comment]
I am a newcomer, do you want to keep on this task?

**Comment by tkuhrt** [comment]
> I am a newcomer, do you want to keep on this task?

Thanks for the comment @a-god-of-death. I believe we are going to close this one for the time being. Please do not hesitate to get involved in the other task forces that exist. We will be discussing task forces in the [upcoming TOC meeting this week](https://zoom-lfx.platform.linuxfoundation.org/meeting/94405985913?password=a2253217-cfbe-462d-ae56-44b57d12d2de).
