### ISSUE TITLE
Move meeting agendas to GitHub

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/tsc#56]
# Why
As we are moving project reports and other items from the Wiki, we should consider whether it makes sense to have all TOC operations in the same location. This will ensure that the meeting minutes are not lost if we migrate from Confluence in the future.

# Proposed Process
1. Hyperledger TOC chair (or vice-chair) will create a pull request to https://github.com/hyperledger/toc to create a file with the meeting agenda in a meetings/YYYY folder. (NOTE: a template will be created to make this easier).
2. During the TOC meeting, the PR will be modified to include the attendees.
3. After the TOC meeting, the PR will be modified to add the recording.
4. The PR will then go through the process of getting two approvals and being merged.

**Comment by ryjones** [comment]
The recordings will continue to live elsewhere, which we can discuss

**Comment by tkuhrt** [comment]
Approved in Feb 2, 2023 meeting by roll call vote. Discussed in the meeting using archive.org as a location for recordings.
