### ISSUE TITLE
Please add AnonCreds to the Hyperledger LFX Insights Metrics

### ISSUE THREAD

**Issue by swcurran** [hyperledger/tsc#63]
Please add Hyperledger AnonCreds so that it shows up here: https://insights.lfx.linuxfoundation.org/projects/hyperledger-f/dashboard;quicktime=time_filter_3Y

Should have just the 3 repos initially.

Thanks!

**Comment by ryjones** [comment]
Hi, @swcurran . [AnonCreds](https://insights-v2.lfx.linuxfoundation.org/anoncreds/trends) is in version 2, but not version 1. I can't add new projects to version 1.

**Comment by swcurran** [comment]
So I should use that in the quarterly reports?  Should it be used for all projects?

Is there any way to get custom dates into that version?  I can get (for example), the last 90 days, but that does not cover the date range of the quarter.  Or is it not worth the trouble of showing the activity for the specific period of the report.

BTW — I’ve assumed that when I do the “Q1 2023” quarterly report, the period of the report is October - December 2022. Is my assumption right?  I cut off my report as of the end of the previous quarter.

**Comment by ryjones** [comment]
@swcurran I think that's the idea. I don't know how to make v2 work like v1. @tkuhrt @arsulegai thoughts?

**Comment by tkuhrt** [comment]
I like links that give you the same results every time you click on it. The last 90 days will change based on when I click on the link, which will not show the data that I may be looking for. We have talked in the past about doing screen captures to avoid the links that change.

Related to the dates, I think that as long as the project is consistent in how they report the data, then that is what counts. I have seen some that do from the last time they submitted the report to the day that they are submitting the new report. I have seen others that pick the last quarter (so like @swcurran mentions using the Q4 data for Q1 and Q1 data for Q2 and so forth).

**Comment by ryjones** [comment]
@tkuhrt I've filed a PR for V1 to add anoncreds. It will take a while to happen.

**Comment by ryjones** [comment]
[done](https://insights.lfx.linuxfoundation.org/projects/hyperledger%2Fanoncreds/dashboard;subTab=technical?time=%7B%22from%22:%222022-10-01T07:00:00.000Z%22,%22type%22:%22absolute%22,%22to%22:%222022-12-31T07:00:00.000Z%22%7D)
