### ISSUE TITLE
Move Grid to EOL status

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger/tsc#82]
* See [conversation with @vaporos on Discord](https://discord.com/channels/905194001349627914/941369600841502792/1085291730741497999)
* [Last commit September 12, 2022 by @ryjones](https://github.com/hyperledger/grid/commit/e1b5843875ea6891176175af178840b770a6aecd)
* [Last commit by maintainers August 26, 2022 by @agunde406](https://github.com/hyperledger/grid/commit/343158678ef9a2e7587d502f0ad33137aacd6356)

cc: @hyperledger/grid-contributors

**Comment by denyeart** [comment]
Seems reasonable, agree.

**Comment by jimthematrix** [comment]
yes vote for me as well

**Comment by ryjones** [comment]
So far we have a thumbs up from two maintainers, @agunde406 and @dcmiddle. @vaporos has expressed his support in Discord. Three TOC members have voted yes: @jimthematrix @denyeart and @lehors

**Comment by peterschwarz** [comment]
Works for me, as a maintainer of grid

**Comment by ryjones** [comment]
Thanks. If @agunde406 @peterschwarz @dcmiddle and @vaporos could approve the PRs, it would make it easier to merge. I won't merge until the TOC votes.

**Comment by ryjones** [comment]
this was approved.

**Comment by koptan** [comment]
but why? no business values or no maintainers? I see a lot of developers in Discord been asking how to run the stack and they need to know how to do some modifications also.
