### ISSUE TITLE
Move Ursa to EOL

### ISSUE THREAD

**Issue by mikelodder7** [hyperledger/tsc#96]
See https://github.com/hyperledger/ursa/pull/233

No major updates have occurred in almost 2 years. There are two major security vulnerabilities against ursa that the maintainers do not have to time to fix and the code is very outdated which is part of the time to fix.

The current maintainers recommend EOL for Ursa.

**Comment by ryjones** [comment]
[Approved 27 APR 2023](https://toc.hyperledger.org/meeting-minutes/2023/2023-04-27-TOC-meeting-record.html)
